import { Montserrat } from 'next/font/google';
import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const MontserratFont = Montserrat({
  subsets: ['latin'],
  display: 'swap',
  weight: ['400', '700'],
  style: 'normal'
});

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang='en'>
      <body className={`${MontserratFont.className} antialiased`}>
        {children}
      </body>
    </html>
  );
}
